-- MySQL Script generated by MySQL Workbench
-- Sun Jul 25 22:55:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cefetmg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cefetmg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cefetmg` DEFAULT CHARACTER SET utf8 ;
USE `cefetmg` ;

-- -----------------------------------------------------
-- Table `cefetmg`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cefetmg`.`employee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`employee_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cefetmg`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `employee_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_employee_employee_type1_idx` (`employee_type_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `matricula_UNIQUE` (`code` ASC) VISIBLE,
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cefetmg`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee_type1`
    FOREIGN KEY (`employee_type_id`)
    REFERENCES `cefetmg`.`employee_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cefetmg`.`resource_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`resource_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_ai` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cefetmg`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`resource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `resource_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resource_department1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_resource_resource_type1_idx` (`resource_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_resource_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `cefetmg`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_resource_type1`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `cefetmg`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cefetmg`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cefetmg`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resource_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `resource_id`, `employee_id`),
  INDEX `fk_schedule_resource1_idx` (`resource_id` ASC) VISIBLE,
  INDEX `fk_schedule_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `cefetmg`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_schedule_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `cefetmg`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
